stages:
  - lint
  - test

variables:
  POSTGRES_USER: 'url_shortener'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_url_shortener'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

pytest:
  stage: test
  image: python:3.7
  tags:
    - docker
  services:
    - postgres:11
  variables:
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB

  before_script:
    - pip install -r requirements/local.txt

  script:
    - pytest

