# Generated by Django 3.0.5 on 2020-04-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0002_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name': 'Url shortened', 'verbose_name_plural': 'Urls shortened'},
        ),
        migrations.RemoveField(
            model_name='urls',
            name='short_url',
        ),
        migrations.AddField(
            model_name='urls',
            name='short_uri',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
